version: '3.8'
services:
  backend_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: app.py
    command: sh -c "python app.py"
    ports:
      - 8005:8005
    volumes:
      - .:/app
